spring:
  jpa:
    hibernate:
      ddl-auto: create
  datasource:
    url: jdbc:mysql://localhost:3307/shopping_cart
    username: root
    password: password
    initialization-mode: always

app:
  factor:
    discount: 0.9
    increase: 1.3
  discount:
    min:
      size: 3